import { addDays, format, subDays } from 'date-fns';
import type { Data, Patient, Visit } from './types';
import { productNames } from './clinical';
const iso = (offset: number) => format(addDays(new Date(), offset), 'yyyy-MM-dd');
export const newVisit = (id: string, patientId: string, woundId: string): Visit => ({ id, patientId, woundId, date: new Date().toISOString(), scheduledTime: '09:00', state: 'Rascunho', step: 0, length: '', width: '', depth: '', tunnels: '', edges: [], perilesional: [], tissue: { Granulação: 100, Epitelização: 0, Esfacelo: 0, 'Necrose seca': 0, 'Necrose úmida': 0, Hipergranulação: 0 }, exudateAmount: 'Pequena', exudateType: 'Seroso', odor: 'Ausente', infection: [], pain: 0, assessments: [], dressings: [], therapies: [], photos: [], plan: '', guidance: '', returnDate: '', signature: [], signedBy: '' });
export function demoData(): Data {
  const names = ['Maria Helena Santos', 'João Carlos Oliveira', 'Ana Lúcia Ferreira', 'Antônio Rodrigues', 'Lúcia Maria Costa', 'José Roberto Almeida'];
  const colors = demoPatientColors;
  const patients: Patient[] = names.map((name, i) => ({ id: `demo-p-${i}`, name, birthDate: `${1958 + i * 2}-0${i + 1}-14`, sex: i % 2 === 0 ? 'Feminino' : 'Masculino', cpf: '', sus: '', phone: '', address: 'Dados fictícios para demonstração', emergency: '', status: 'Ativo', weight: 68 + i * 3, height: 162 + i * 2, bloodType: ['O+', 'A+', 'B+'][i % 3], allergies: i === 0 ? ['Dipirona', 'Látex'] : [], smoking: 'Não', alcohol: 'Não', activity: 'Caminhada leve', comorbidities: [{ name: i % 2 === 0 ? 'Insuficiência venosa crônica' : 'Diabetes mellitus tipo 2', date: '2020-06-15', note: 'Em acompanhamento' }, { name: 'Hipertensão arterial sistêmica', date: '2018-03-10', note: '' }], medications: [{ name: 'Losartana', dose: '50 mg', route: 'Oral', frequency: '1 vez ao dia', start: '2020-06-15', indication: 'Hipertensão', attention: false }], exams: [{ type: 'HbA1c', value: '6,8 %', date: iso(-20) }], color: colors[i], createdAt: iso(-60) }));
  const wounds = patients.map((p, i) => ({ id: `demo-w-${i}`, patientId: p.id, location: ['Maléolo medial esquerdo', 'Região plantar direita', 'Perna direita', 'Região sacral', 'Maléolo lateral direito', 'Calcâneo esquerdo'][i], etiology: ['Venosa', 'Pé diabético', 'Venosa', 'Pressão', 'Venosa', 'Arterial'][i], startDate: iso(-70 - i * 7), status: (i === 3 ? 'Estagnada' : 'Em cicatrização') as Data['wounds'][number]['status'], previousTreatments: 'Limpeza e cobertura conforme avaliação anterior.', pin: { x: 100, y: 280, side: 'Frente' as const } }));
  const visits: Visit[] = [];
  patients.forEach((p, i) => {
    [28, 21, 14, 7].forEach((days, j) => visits.push({ ...newVisit(`demo-v-${i}-${j}`, p.id, wounds[i].id), state: 'Concluído', date: subDays(new Date(), days + i % 2).toISOString(), length: String(i === 3 ? 3 : 5 - j * 0.6), width: String(i === 3 ? 2 : 3 - j * 0.35), depth: '0.2', plan: 'Higienização e troca de cobertura. Manter acompanhamento da evolução.', guidance: 'Mantenha a cobertura limpa e seca. Retorne na data combinada.', signedBy: 'Caroline Ferreira (demonstração)', returnDate: iso(i < 3 ? 0 : i - 2), signature: [[{ x: 15, y: 30 }, { x: 40, y: 10 }, { x: 60, y: 32 }]] }));
    visits.push({ ...newVisit(`demo-s-${i}`, p.id, wounds[i].id), state: 'Agendado', date: `${iso(i < 3 ? 0 : i - 2)}T${['09:00', '10:30', '14:00', '09:30', '11:00', '15:00'][i]}:00`, scheduledTime: ['09:00', '10:30', '14:00', '09:30', '11:00', '15:00'][i] });
  });
  return { patients, wounds, visits, reports: [], profiles: [{ id: 'demo', name: 'Caroline Ferreira', council: 'COREN', registration: 'Demonstração', specialty: 'Enfermagem estomaterapeuta' }], products: productNames.map((name, i) => ({ id: `demo-product-${i}`, name, presentation: '' })) };
}
export const demoPatientColors = ['#FDECEC', '#F8D8D8', '#F4C2C2', '#FCE5E5', '#F7D0D0', '#FDECEC'];
