import React, { useState } from 'react';
import { ActivityIndicator, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View, type StyleProp, type ViewStyle, type TextStyle } from 'react-native';
import * as Haptics from 'expo-haptics';
import { ChevronDown, ChevronRight, CircleHelp, Plus, X, type LucideIcon } from 'lucide-react-native';
import { colors as c, fonts } from './theme';
export function Txt({ children, style, muted, ...props }: React.ComponentProps<typeof Text> & { muted?: boolean }) { return <Text {...props} style={[s.text, muted && { color: c.secondary }, style]}>{children}</Text>; }
export function Label({ children, style }: { children: React.ReactNode; style?: StyleProp<TextStyle> }) { return <Txt style={[s.label, style]}>{children}</Txt>; }
export function Card({ children, style, dark = false }: { children: React.ReactNode; style?: StyleProp<ViewStyle>; dark?: boolean }) { return <View style={[s.card, dark && { backgroundColor: c.dark, borderColor: c.dark }, style]}>{children}</View>; }
export function Button({ title, onPress, icon: Icon, variant = 'primary', small, disabled, loading, style }: { title: string; onPress: () => void; icon?: LucideIcon; variant?: 'primary' | 'dark' | 'outline' | 'ghost'; small?: boolean; disabled?: boolean; loading?: boolean; style?: StyleProp<ViewStyle> }) {
  const color = variant === 'primary' || variant === 'dark' ? '#FFF' : c.text;
  return <Pressable accessibilityRole="button" accessibilityLabel={title} disabled={disabled || loading} onPress={() => { if (Platform.OS !== 'web') void Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light); onPress(); }} style={({ pressed }) => [s.button, { backgroundColor: variant === 'primary' ? (pressed ? c.redPressed : c.red) : variant === 'dark' ? c.dark : variant === 'outline' ? '#FFF' : 'transparent', borderWidth: variant === 'outline' ? 1 : 0, opacity: disabled ? 0.4 : pressed ? 0.8 : 1, paddingHorizontal: small ? 16 : 22 }, style]}>{loading ? <ActivityIndicator size="small" color={color} /> : Icon ? <Icon size={18} color={color} strokeWidth={1.7} /> : null}<Txt style={{ color, fontSize: small ? 13 : 14, fontFamily: fonts.semibold }}>{title}</Txt></Pressable>;
}
export function IconButton({ icon: Icon, label, onPress, color = c.secondary, style }: { icon: LucideIcon; label: string; onPress: () => void; color?: string; style?: StyleProp<ViewStyle> }) { return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={({ pressed }) => [s.iconButton, pressed && { backgroundColor: c.border }, style]}><Icon size={21} strokeWidth={1.7} color={color} /></Pressable>; }
export function Badge({ children, tone = 'neutral', dark }: { children: React.ReactNode; tone?: 'neutral' | 'red' | 'green' | 'amber'; dark?: boolean }) { const theme = { neutral: ['#F3F3F3', c.secondary], red: [c.redSoft, c.red], green: [c.greenSoft, c.green], amber: [c.amberSoft, c.amber] }[tone]; return <View style={[s.badge, { backgroundColor: dark ? '#333333' : theme[0] }]}><Txt style={{ fontSize: 11, fontFamily: fonts.medium, color: dark ? '#F2F2F2' : theme[1] }}>{children}</Txt></View>; }
export function Avatar({ name, color = '#EEE', size = 44, anonymous }: { name: string; color?: string; size?: number; anonymous?: boolean }) { return <View style={{ width: size, height: size, borderRadius: size * 0.36, backgroundColor: color, alignItems: 'center', justifyContent: 'center' }}><Txt style={{ fontFamily: fonts.semibold, fontSize: size * 0.31, color: '#333333' }}>{anonymous ? 'P' : name.split(' ').filter(Boolean).map(n => n[0]).slice(0, 2).join('')}</Txt></View>; }
export function Field({ label, error, style, ...props }: React.ComponentProps<typeof TextInput> & { label: string; error?: string; style?: StyleProp<TextStyle> }) { return <View style={{ gap: 7, flexGrow: 1, flexBasis: 160 }}><Txt style={{ fontSize: 13, fontFamily: fonts.medium }}>{label}</Txt><TextInput accessibilityLabel={label} placeholderTextColor="#777777" {...props} style={[s.input, props.multiline && { minHeight: 100, textAlignVertical: 'top' }, error && { borderColor: c.red }, style]} />{error && <Txt style={{ color: c.red, fontSize: 12 }}>{error}</Txt>}</View>; }
export function Pills({ options, value, onChange }: { options: string[]; value: string; onChange: (value: string) => void }) { return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.pillContainer}>{options.map(option => <Pressable key={option} accessibilityRole="button" accessibilityState={{ selected: value === option }} onPress={() => onChange(option)} style={[s.pill, value === option && { backgroundColor: c.dark }]}><Txt style={{ color: value === option ? '#FFF' : c.secondary, fontFamily: fonts.medium, fontSize: 13 }}>{option}</Txt></Pressable>)}</ScrollView>; }
export function Choices({ options, value, onChange, multiple = false }: { options: string[]; value: string | string[]; onChange: (value: any) => void; multiple?: boolean }) { return <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}>{options.map(option => { const selected = multiple ? (value as string[]).includes(option) : value === option; return <Pressable accessibilityRole="button" accessibilityState={{ selected }} key={option} style={[s.choice, selected && { backgroundColor: c.redSoft, borderColor: '#EDB4B4' }]} onPress={() => onChange(multiple ? selected ? (value as string[]).filter(v => v !== option) : [...value as string[], option] : option)}><Txt style={{ fontSize: 13, color: selected ? c.red : c.secondary }}>{option}</Txt></Pressable>; })}</View>; }
export function SectionTitle({ title, action, onPress }: { title: string; action?: string; onPress?: () => void }) { return <View style={s.between}><Label>{title}</Label>{action && <Pressable onPress={onPress} accessibilityRole="button" style={{ minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 5 }}><Txt style={{ fontSize: 12, color: c.secondary }}>{action}</Txt><ChevronRight size={14} color={c.secondary} /></Pressable>}</View>; }
export function Empty({ title, description, action, onPress, icon: Icon = CircleHelp }: { title: string; description: string; action?: string; onPress?: () => void; icon?: LucideIcon }) { return <View style={{ padding: 32, alignItems: 'center', gap: 12 }}><View style={{ padding: 18, backgroundColor: c.redSoft, borderRadius: 24 }}><Icon size={32} color={c.red} strokeWidth={1.3} /></View><Txt style={{ fontFamily: fonts.semibold, fontSize: 18, textAlign: 'center' }}>{title}</Txt><Txt muted style={{ textAlign: 'center', lineHeight: 22, maxWidth: 320 }}>{description}</Txt>{action && onPress && <Button title={action} onPress={onPress} icon={Plus} small />}</View>; }
export function Accordion({ title, children, initialOpen = false, subtitle }: { title: string; children: React.ReactNode; initialOpen?: boolean; subtitle?: string }) { const [open, setOpen] = useState(initialOpen); return <Card style={{ padding: 0 }}><Pressable accessibilityRole="button" accessibilityState={{ expanded: open }} onPress={() => setOpen(!open)} style={[s.between, { padding: 22 }]}><View style={{ gap: 5, flex: 1 }}><Txt style={{ fontFamily: fonts.semibold, fontSize: 16 }}>{title}</Txt>{subtitle && <Txt muted style={{ fontSize: 12 }}>{subtitle}</Txt>}</View>{open ? <ChevronDown size={18} color={c.secondary} /> : <ChevronRight size={18} color={c.secondary} />}</Pressable>{open && <View style={{ padding: 22, paddingTop: 0, gap: 18 }}>{children}</View>}</Card>; }
export function Divider() { return <View style={{ height: 1, backgroundColor: c.border }} />; }
export function Skeleton() { return <View style={{ gap: 20, padding: 28 }}><View style={{ width: 220, height: 36, backgroundColor: c.border, borderRadius: 12 }} />{[1, 2, 3].map(i => <View key={i} style={{ height: 150, backgroundColor: '#F0F0F0', borderRadius: 24 }} />)}</View>; }
export const s = StyleSheet.create({ text: { fontFamily: fonts.regular, fontSize: 15, color: c.text }, label: { fontSize: 10, letterSpacing: 1.4, color: c.secondary, fontFamily: fonts.semibold }, card: { padding: 24, borderRadius: 24, backgroundColor: c.surface, borderWidth: 1, borderColor: c.border, gap: 16 }, button: { minHeight: 48, borderRadius: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9, borderColor: c.border }, iconButton: { width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center' }, input: { minHeight: 48, borderWidth: 1, borderColor: c.border, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, backgroundColor: '#FFF', color: c.text, fontFamily: fonts.regular, fontSize: 14 }, badge: { alignSelf: 'flex-start', borderRadius: 7, paddingHorizontal: 8, paddingVertical: 5 }, pillContainer: { padding: 5, backgroundColor: '#FFF', borderRadius: 28, borderWidth: 1, borderColor: c.border, gap: 4, alignSelf: 'flex-start' }, pill: { minHeight: 42, justifyContent: 'center', paddingHorizontal: 20, borderRadius: 24 }, choice: { borderWidth: 1, borderColor: c.border, paddingHorizontal: 14, minHeight: 48, justifyContent: 'center', borderRadius: 12 }, between: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 }, row: { flexDirection: 'row', alignItems: 'center', gap: 12 }, wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 16 }, h1: { fontFamily: fonts.brand, fontSize: 28, lineHeight: 38 }, h2: { fontFamily: fonts.semibold, fontSize: 18 }, muted: { color: c.secondary } });
