import { useState } from 'react';
import { ScrollView, View, Pressable } from 'react-native';
import { CalendarDays, ChevronRight, Plus } from 'lucide-react-native';
import { useRouter } from 'expo-router';
import { Card, Button, Empty, Label, Pills, SectionTitle, Txt, s, Avatar, Badge } from '../../src/ui/components';
import { colors as c, fonts } from '../../src/ui/theme';
import { dateLabel } from '../../src/domain/clinical';
import { useStore } from '../../src/data/store';
export default function CareList() { const router = useRouter(); const { visits, patients, wounds } = useStore(st => st.data); const days = ['Hoje', 'Amanhã', 'Esta semana']; const [day, setDay] = useState('Hoje'); const agenda = visits.filter(v => v.state === 'Agendado').sort((a, b) => a.date.localeCompare(b.date)); return <View style={{ flex: 1, backgroundColor: c.bg }}><ScrollView contentContainerStyle={{ padding: 24, paddingTop: 25, paddingBottom: 170, gap: 22 }}><View style={s.between}><View><Txt muted style={{ fontSize: 13 }}>AGENDA CLÍNICA</Txt><Txt style={s.h1}>Atendimento</Txt></View><Button title="Novo" icon={Plus} small onPress={() => router.push('/care/new')} /></View><Pills options={days} value={day} onChange={setDay} /><View style={{ gap: 12 }}><SectionTitle title="PRÓXIMOS ATENDIMENTOS" />{agenda.map(v => { const p = patients.find(x => x.id === v.patientId); const w = wounds.find(x => x.id === v.woundId); if (!p || !w) return null; return <Pressable key={v.id} onPress={() => router.push(`/care/${v.id}`)}><Card style={{ padding: 18, flexDirection: 'row', alignItems: 'center' }}><Avatar name={p.name} color={p.color} size={46} /><View style={{ flex: 1, marginLeft: 12, gap: 4 }}><Txt style={{ fontFamily: fonts.semibold }}>{p.name}</Txt><Txt muted style={{ fontSize: 12 }}>{v.scheduledTime} · {w.location}</Txt><Badge tone={w.status === 'Estagnada' ? 'amber' : 'green'}>{w.status}</Badge></View><ChevronRight size={19} color={c.tertiary} /></Card></Pressable>; })}{agenda.length === 0 && <Card><Empty icon={CalendarDays} title="Agenda livre" description="Comece um atendimento para registrar a evolução de uma ferida." action="Novo atendimento" onPress={() => router.push('/care/new')} /></Card>}</View></ScrollView></View>; }
